spring.application.name=KALARO-ORDERS

server.port=9090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/kalaro_order
spring.datasource.username=postgres
spring.datasource.password=bbw@8138

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs